Repository SWM-KAWAI-MANS/party-run-matching-service, pull requests merged in 2023-07, with the labels that each got.

#3 feat : gradle-spring project를 초기 설정 PAR-181
  build.gradle
  settings.gradle
  src/main/java/online/partyrun/partyrunmatchingservice/PartyRunMatchingServiceApplication.java
  src/test/java/online/partyrun/partyrunmatchingservice/PartyRunMatchingServiceApplicationTests.java
Labels: ✨ 기능

#4 feat : webflux security 및 jwt 설정 #PAR-182
  build.gradle
  src/main/java/online/partyrun/partyrunmatchingservice/global/security/AuthUser.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/security/AuthorizationException.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/security/WebfluxAuthFilter.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/security/WebfluxSecurityConfig.java
  src/main/resources/application.yml
  src/test/java/online/partyrun/partyrunmatchingservice/global/security/AuthUserTest.java
Labels: ✨ 기능

#5 feat: SSE Event Handler 구현
  src/main/java/online/partyrun/partyrunmatchingservice/global/sse/MultiSinkHandler.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/sse/ServerSentEventHandler.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/sse/exception/KeyNotExistException.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/sse/exception/NullKeyException.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/sse/exception/SseConnectionException.java
  src/test/java/online/partyrun/partyrunmatchingservice/global/sse/MultiSinkHandlerTest.java
Labels: ✨ 기능

#6 Waiting 생성 API 요청 응답 처리 Controller 구현 #PAR-180
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/controller/WaitingController.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/dto/CreateWaitingRequest.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/dto/WaitingEvent.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingService.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/dto/MessageResponse.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/sse/MultiSinkHandler.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/sse/exception/KeyNotExistException.java
  src/test/java/online/partyrun/partyrunmatchingservice/config/docs/WebfluxDocsTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/controller/WaitingControllerTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingServiceTest.java
Labels: ✨ 기능

#7 feat : waiting 관련 SSE 구독 로직 구현
  src/docs/asciidoc/index.adoc
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/controller/WaitingController.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/dto/WaitingStatus.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingService.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/sse/MultiSinkHandler.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/controller/WaitingControllerTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingServiceTest.java
Labels: ✨ 기능

#8 feat : redis pub-sub 설정 및 waiting 유저 정보를 multicast로 전송/구독 구현 #PAR-186 #PAR-188
  build.gradle
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/controller/WaitingController.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/exception/DuplicateMemberException.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/exception/NotAllowMeterException.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/exception/NotSatisfyCountException.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/message/WaitingMessageConfig.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/message/WaitingMessagePublisher.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/InMemoryWaitingQueue.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/WaitingQueue.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/root/RunningDistance.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/root/WaitingMember.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventService.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingMessageListener.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingService.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/db/redis/RedisChannel.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/sse/MultiSinkHandler.java
  src/test/java/online/partyrun/partyrunmatchingservice/PartyRunMatchingServiceApplicationTests.java
  src/test/java/online/partyrun/partyrunmatchingservice/config/redis/RedisTestConfig.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/controller/WaitingControllerTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/InMemoryWaitingQueueTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/root/RunningDistanceTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventServiceTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingProcessTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingServiceTest.java
Labels: ✨ 기능

#9 feat : Matching 생성 로직 구현 #PAR-190
  build.gradle
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/Matching.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/MatchingMember.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/MatchingMemberStatus.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/MatchingStatus.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/exception/InvalidDistanceException.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/exception/InvalidIdException.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/exception/InvalidMembersException.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/repository/MatchingRepository.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingService.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/dto/WaitingStatus.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventService.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingMessageListener.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/mongo/MongoConfig.java
  src/main/resources/application.yml
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/MatchingMemberTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/MatchingTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingServiceTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventServiceTest.java
Labels: ✨ 기능

#13 feat : Matching 생성 시 SSE sink 생성하도록 구현
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/dto/MatchEvent.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/Matching.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/MatchingMember.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/repository/MatchingRepository.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingService.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingSinkHandler.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventService.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingSinkHandler.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/sse/ServerSentEventHandler.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/sse/SinkHandlerTemplate.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/MatchingMemberTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/MatchingTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/repository/MatchingRepositoryTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingServiceTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventServiceTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/global/sse/SinkHandlerTemplateTest.java
Labels: ✨ 기능

#15 test : waiting event 관련 테스트 병합
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventServiceTest.java
Labels: ♻️ 리팩토링

#16 feat : 클라이언트가 matching에 대한 수락/거절 요청 전송 구현 #PAR-193
  src/docs/asciidoc/index.adoc
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingController.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingRequest.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/Matching.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/MatchingMember.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/MatchingMemberStatus.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/MatchingStatus.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/repository/MatchingRepository.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingService.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingControllerTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/MatchingTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/repository/MatchingRepositoryTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingServiceTest.java
Labels: ✨ 기능

#17 feat : jib setting
  build.gradle
Labels: ✨ 기능

#18 Github actions + docker를 활용하여 ci/cd 파이프라인을 생성한다.
  .github/workflows/build-docker-image-dev.yml
  .github/workflows/cd-dev.yml
  build.gradle
Labels: 🏭인프라

#19 feat : mongo, redis URI 변수 설정
  src/main/resources/application.yml
Labels: ✨ 기능

#20 feat : matching event 구독 및 이벤트 스트림 응답 로직 구현
  src/docs/asciidoc/index.adoc
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingController.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingService.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingControllerTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingServiceTest.java
Labels: ✨ 기능

#21 refactor : matchingService 로직 메서드 추출 리펙터링
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingService.java
Labels: ♻️ 리팩토링
