Repository SWM-KAWAI-MANS/party-run-matching-service, pull requests merged in 2023-08, with the labels that each got.

#22 refactor : waitingQueue, matchingSerivce 부분 리펙터링
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingService.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/InMemoryWaitingQueue.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/WaitingQueue.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingMessageListener.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/InMemoryWaitingQueueTest.java
Labels: ♻️ 리팩토링

#23 로그 출력을 위한 파일을 생성한다.
  .gitignore
  src/main/resources/logback-spring.xml
Labels: ✨ 기능

#24 feat : matching/waiting에서 무응답한 SSE Sink 주기적으로 삭제 #PAR-189
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/Matching.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/repository/MatchingRepository.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingService.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/InMemoryWaitingQueue.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/WaitingQueue.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventService.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingService.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/config/ScheduleConfig.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/config/TimeConfig.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingControllerTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/MatchingTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/repository/MatchingRepositoryTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingServiceTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventServiceTest.java
Labels: ✨ 기능

#25 feat : controller advice 설정
  src/docs/asciidoc/index.adoc
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/Matching.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/MatchingMember.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/exception/InvalidDistanceException.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/exception/InvalidIdException.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/exception/InvalidMatchingIdException.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/exception/InvalidMembersException.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/exception/NotExistMembersException.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/exception/DuplicateMemberException.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/exception/InvalidDistanceException.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/exception/NotAllowDistanceException.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/exception/NotSatisfyCountException.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/root/RunningDistance.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/controller/HttpControllerAdvice.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/exception/BadRequestException.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/exception/InternalServerException.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/exception/InvalidSinksKeyException.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/exception/SseConnectionException.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingControllerTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/MatchingMemberTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/MatchingTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/controller/WaitingControllerTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/root/RunningDistanceTest.java
Labels: ✨ 기능

#27 fix : change waiting-event response format
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/controller/WaitingController.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/dto/WaitingEventResponse.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventService.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventServiceTest.java
Labels: ♻️ 리팩토링

#29 refactor : matching status 삭제 및 matching confirm 부분 스레드 분할
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingController.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/Matching.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/repository/MatchingRepository.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingService.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingControllerTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/repository/MatchingRepositoryTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingServiceTest.java
Labels: ♻️ 리팩토링

#30 feat : matching 완료 시 battle 생성 후 battle id를 이벤트에 포함하도록 구현
  build.gradle
  src/main/java/online/partyrun/partyrunmatchingservice/domain/battle/service/BattleService.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/battle/service/external/ExternalBattleService.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/battle/service/external/dto/BattleResponse.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/battle/service/external/dto/CreateBattleRequest.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/battle/service/external/exception/BattleAlreadyExistException.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/dto/MatchEvent.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/Matching.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingService.java
  src/main/resources/application.yml
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/MatchingStatusTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingServiceTest.java
Labels: ✨ 기능

#32 feat : id를 통한 matching 조회 api 구현
  src/docs/asciidoc/index.adoc
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingController.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/dto/MatchingMemberResponse.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/dto/MatchingResponse.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingService.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingControllerTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingServiceTest.java
Labels: ✨ 기능

#33 refactor : 매칭 참여 여부 API 엔드포인트 변경
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingController.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingControllerTest.java
Labels: ♻️ 리팩토링

#34 refactor : Matching 조회 로직 수정
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingController.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/dto/MatchingMembersResponse.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/dto/MatchingResponse.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingService.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingControllerTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingServiceTest.java
Labels: ♻️ 리팩토링

#35 fix : matching 상태 update 로직 싱글 스레드에서 동작하도록 변경
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingService.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingServiceTest.java
Labels: 🐛 버그

#36 fix : 최근 매칭 탐색 repository 로직 변경
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/repository/MatchingRepository.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingService.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/repository/MatchingRepositoryTest.java
Labels: ✨ 기능

#37 feat : event 구독 이후 클라이언트 cancel 시 내부 로직 구현
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/InMemoryWaitingQueue.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/WaitingQueue.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingSinkHandler.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/sse/SinkHandlerTemplate.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/InMemoryWaitingQueueTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventServiceTest.java
Labels: ✨ 기능

#38 feat : waiting event 취소 API 구현
  src/docs/asciidoc/index.adoc
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/controller/WaitingController.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventService.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/controller/WaitingControllerTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventServiceTest.java
Labels: ✨ 기능

#40 refactor : google reformat 삭제
  .github/workflows/reformat-java.yml
Labels: ♻️ 리팩토링

#39 feat : 전역 Debug log 설정
  build.gradle
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingSinkHandler.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/advisor/LogAdvisor.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/sse/SinkHandlerTemplate.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventServiceTest.java
Labels: ✨ 기능

#41 refactor : intellij default 기준 reformat 변경
  src/main/java/online/partyrun/partyrunmatchingservice/domain/battle/service/external/ExternalBattleService.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/battle/service/external/dto/BattleResponse.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/battle/service/external/dto/CreateBattleRequest.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingController.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingRequest.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/Matching.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/MatchingMember.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/repository/MatchingRepository.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingService.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingSinkHandler.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/controller/WaitingController.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/dto/CreateWaitingRequest.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/message/WaitingMessageConfig.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/message/WaitingMessagePublisher.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/InMemoryWaitingQueue.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/root/RunningDistance.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventService.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingMessageListener.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingService.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingSinkHandler.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/advisor/LogAdvisor.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/config/ScheduleConfig.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/controller/HttpControllerAdvice.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/db/redis/RedisChannel.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/dto/MessageResponse.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/mongo/MongoConfig.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/security/AuthUser.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/security/WebfluxAuthFilter.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/security/WebfluxSecurityConfig.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/sse/SinkHandlerTemplate.java
Labels: ♻️ 리팩토링

#42 refactor : waiting cancel 시 status 변경
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/controller/WaitingController.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/controller/WaitingControllerTest.java
Labels: ♻️ 리팩토링

#43 refactor : waiting(Event)Service 함수 추출 및 map - doOnNext 부분 분할 리펙터링
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventService.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingService.java
Labels: ♻️ 리팩토링

#44 feat : waiting cancel시 Event 추가
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/dto/WaitingStatus.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventService.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventServiceTest.java
Labels: ✨ 기능

#46 fix : inmemory queue redis로 대체
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/controller/WaitingController.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/message/WaitingMessageConfig.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/message/WaitingMessagePublisher.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/InMemoryWaitingQueue.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/WaitingQueue.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/redis/RedisWaitingConfig.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/redis/WaitingQueue.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/CreateWaitingService.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingCheckService.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventService.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingMessageListener.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/sse/ServerSentEventHandler.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/sse/SinkHandlerTemplate.java
  src/main/resources/application.yml
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/controller/WaitingControllerTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/InMemoryWaitingQueueTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/redis/WaitingQueueTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/CreateWaitingServiceTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventServiceTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingProcessTest.java
Labels: ♻️ 리팩토링, ✨ 기능
