Repository SWM-KAWAI-MANS/party-run-matching-service, pull requests merged in 2023-09, with the labels that each got.

#47 fix : inmemory queue redis로 대체 (#46)
  .github/workflows/build.yml
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/controller/WaitingController.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/message/WaitingMessageConfig.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/message/WaitingMessagePublisher.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/InMemoryWaitingQueue.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/WaitingQueue.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/redis/RedisWaitingConfig.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/redis/WaitingQueue.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/CreateWaitingService.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingCheckService.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventService.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingMessageListener.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/advisor/LogAdvisor.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/sse/ServerSentEventHandler.java
  src/main/java/online/partyrun/partyrunmatchingservice/global/sse/SinkHandlerTemplate.java
  src/main/resources/application.yml
  src/test/java/online/partyrun/partyrunmatchingservice/config/redis/RedisTestConfig.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingServiceTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/controller/WaitingControllerTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/InMemoryWaitingQueueTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/redis/WaitingQueueTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/CreateWaitingServiceTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingCheckServiceTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventServiceTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingProcessTest.java
Labels: ♻️ 리팩토링, ✨ 기능, 🐛 버그

#51 feat : 같이하기(party) 관련 API 구현
  src/docs/asciidoc/index.adoc
  src/main/java/online/partyrun/partyrunmatchingservice/domain/party/controller/PartyController.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/party/dto/PartyEvent.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/party/dto/PartyIdResponse.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/party/dto/PartyRequest.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/party/entity/EntryCode.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/party/entity/Party.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/party/entity/PartyStatus.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/party/repository/PartyRepository.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/party/service/PartyService.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/party/service/PartySinkHandler.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingServiceTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/party/controller/PartyControllerTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/party/entity/EntryCodeTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/party/entity/PartyTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/party/service/PartyServiceTest.java
Labels: ✨ 기능

#53 refactor : party leader -> manager로 네이밍 변경 및 party event에 distance 추가
  src/main/java/online/partyrun/partyrunmatchingservice/domain/party/dto/PartyEvent.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/party/entity/Party.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/party/controller/PartyControllerTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/party/service/PartyServiceTest.java
Labels: ♻️ 리팩토링

#54 feat : party 나가기 기능 구현
  src/main/java/online/partyrun/partyrunmatchingservice/domain/party/entity/Party.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/party/entity/PartyStatus.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/party/service/PartyService.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/party/entity/PartyTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/party/service/PartyServiceTest.java
Labels: ✨ 기능

#55 feat : Party Validation 로직 추가
  src/docs/asciidoc/index.adoc
  src/main/java/online/partyrun/partyrunmatchingservice/domain/party/dto/PartyEvent.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/party/entity/Party.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/party/exception/IllegalArgumentIdException.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/party/exception/NotSatisfyMemberCountException.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/party/exception/PartyClosedException.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/party/exception/PartyNotFoundException.java
  src/main/java/online/partyrun/partyrunmatchingservice/domain/party/service/PartyService.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/party/controller/PartyControllerTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/party/entity/PartyTest.java
  src/test/java/online/partyrun/partyrunmatchingservice/domain/party/service/PartyServiceTest.java
Labels: ✨ 기능

#56 ci cd prd 설정
  .github/workflows/build-docker-image-prd.yml
  .github/workflows/cd-prd.yml
Labels: 🏭인프라
